name: aptis-lms

services:
  postgres:
    image: postgres:17
    container_name: aptis-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_PORT:-5432}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

    networks:
      - aptis-network

  api:
    container_name: aptis-api
    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    environment:
      DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_SECONDS: ${JWT_EXPIRATION_SECONDS}

      ADMIN_SEED_EMAIL: ${ADMIN_SEED_EMAIL}
      ADMIN_SEED_PASSWORD: ${ADMIN_SEED_PASSWORD}

      HOST_SEED_CODE: ${HOST_SEED_CODE}
      HOST_SEED_NAME: ${HOST_SEED_NAME}
      HOST_SEED_EMAIL: ${HOST_SEED_EMAIL}
      HOST_SEED_PASSWORD: ${HOST_SEED_PASSWORD}
      HOST_SEED_ORGANIZATION_NAME: ${HOST_SEED_ORGANIZATION_NAME}
      HOST_SEED_ORGANIZATION_TYPE: ${HOST_SEED_ORGANIZATION_TYPE}
      HOST_SEED_ORGANIZATION_ADDRESS: ${HOST_SEED_ORGANIZATION_ADDRESS}
      HOST_SEED_REPRESENTATIVE_NAME: ${HOST_SEED_REPRESENTATIVE_NAME}
      HOST_SEED_REPRESENTATIVE_PHONE: ${HOST_SEED_REPRESENTATIVE_PHONE}
      HOST_SEED_CONTRACT_CODE: ${HOST_SEED_CONTRACT_CODE}
      HOST_SEED_PACKAGE_NAME: ${HOST_SEED_PACKAGE_NAME}
      HOST_SEED_STUDENT_LIMIT: ${HOST_SEED_STUDENT_LIMIT}

      STUDENT_SEED_USERNAME: ${STUDENT_SEED_USERNAME}
      STUDENT_SEED_PASSWORD: ${STUDENT_SEED_PASSWORD}
      STUDENT_SEED_FULL_NAME: ${STUDENT_SEED_FULL_NAME}
      STUDENT_SEED_CODE: ${STUDENT_SEED_CODE}
      STUDENT_SEED_CLASS_NAME: ${STUDENT_SEED_CLASS_NAME}
      STUDENT_SEED_EMAIL: ${STUDENT_SEED_EMAIL}
      STUDENT_SEED_PHONE: ${STUDENT_SEED_PHONE}

      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}

    ports:
      - "${API_PORT}:8080"

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - aptis-network

volumes:
  postgres_data:
    name: aptis-api_postgres_data

networks:
  aptis-network:
    driver: bridge
