-- scoring module (plans/modular-monolith Phase 08).
-- Hand-written to match what Hibernate derives from ScoringAnswer (extends
-- shared.domain.BaseEntity), not copied from services/scoring (ddl-auto:
-- update there, no Flyway migration of its own).

CREATE TABLE IF NOT EXISTS scoring_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    answer_public_id UUID NOT NULL UNIQUE,
    attempt_public_id UUID NOT NULL,
    pinned_item_public_id UUID NOT NULL,
    session_public_id UUID NOT NULL,
    tenant_id UUID NOT NULL,
    task_type VARCHAR(64) NOT NULL,
    payload TEXT,
    correct_answer_text TEXT,
    options_json TEXT,
    expired BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(16) NOT NULL,
    raw_score INTEGER,
    scored_at TIMESTAMP WITH TIME ZONE,
    teacher_score INTEGER,
    teacher_scored_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_scoring_answers_session ON scoring_answers (session_public_id);
CREATE INDEX IF NOT EXISTS idx_scoring_answers_attempt ON scoring_answers (attempt_public_id);
CREATE INDEX IF NOT EXISTS idx_scoring_answers_status ON scoring_answers (status);
CREATE INDEX IF NOT EXISTS idx_scoring_answers_tenant_review ON scoring_answers (tenant_id, session_public_id, status, created_at);
