-- proctoring module (plans/modular-monolith Phase 09).
-- Hand-written to match what Hibernate derives from ProctorSession/ViolationEvent
-- (extend shared.domain.BaseEntity), not copied from services/proctor
-- (ddl-auto: update there, no Flyway migration of its own).

CREATE TABLE IF NOT EXISTS proctor_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    session_public_id UUID NOT NULL,
    proctor_public_id UUID NOT NULL,
    tenant_id UUID NOT NULL,
    status VARCHAR(16) NOT NULL,
    opened_at TIMESTAMP WITH TIME ZONE NOT NULL,
    closed_at TIMESTAMP WITH TIME ZONE,
    last_sequence_no INTEGER NOT NULL DEFAULT 0,
    last_hash VARCHAR(64)
);

CREATE INDEX IF NOT EXISTS idx_proctor_sessions_session_proctor ON proctor_sessions (session_public_id, proctor_public_id);
CREATE INDEX IF NOT EXISTS idx_proctor_sessions_tenant ON proctor_sessions (tenant_id);

CREATE TABLE IF NOT EXISTS violation_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    proctor_session_id BIGINT NOT NULL REFERENCES proctor_sessions (id),
    session_public_id UUID NOT NULL,
    attempt_public_id UUID NOT NULL,
    tenant_id UUID NOT NULL,
    violation_type VARCHAR(32) NOT NULL,
    detail TEXT,
    sequence_no INTEGER NOT NULL,
    prev_hash VARCHAR(64),
    hash VARCHAR(64) NOT NULL,
    detected_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_violation_events_session ON violation_events (proctor_session_id);
CREATE INDEX IF NOT EXISTS idx_violation_events_exam_session ON violation_events (session_public_id);
CREATE INDEX IF NOT EXISTS idx_violation_events_attempt ON violation_events (attempt_public_id);
