-- notification module (plans/modular-monolith Phase 09).
-- Hand-written to match what Hibernate derives from NotificationLog (extends
-- shared.domain.BaseEntity), not copied from services/notification
-- (ddl-auto: update there, no Flyway migration of its own).

CREATE TABLE IF NOT EXISTS notification_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    recipient_user_public_id UUID NOT NULL,
    recipient_email VARCHAR(255) NOT NULL,
    tenant_id UUID NOT NULL,
    notification_type VARCHAR(32) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    status VARCHAR(16) NOT NULL,
    sent_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_notification_logs_tenant ON notification_logs (tenant_id);
