-- reporting module (plans/modular-monolith Phase 10).
-- Hand-written to match what Hibernate derives from AttemptReport (extends
-- shared.domain.BaseEntity), not copied from services/reporting (ddl-auto:
-- update there, no Flyway migration of its own).

CREATE TABLE IF NOT EXISTS attempt_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    attempt_public_id UUID NOT NULL UNIQUE,
    session_public_id UUID NOT NULL,
    student_public_id UUID NOT NULL,
    tenant_id UUID NOT NULL,
    published BOOLEAN NOT NULL DEFAULT FALSE,
    published_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_attempt_reports_session ON attempt_reports (session_public_id);
