-- scoretemplate module (plans/score-template-exam-generation, Plan A / Phase 1).
-- Hand-written to match what Hibernate derives from ScoreTemplate/ScoreTemplateItem
-- (extend shared.domain.BaseEntity), following the same convention as
-- V6__itembank.sql / V7__assessment.sql.
--
-- gen_random_uuid() is Postgres 17 core (no CREATE EXTENSION needed, unlike
-- pre-13 pgcrypto-based setups) — this project's docker-compose pins postgres:17.

CREATE TABLE IF NOT EXISTS score_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    code VARCHAR(64) NOT NULL,
    version INTEGER NOT NULL,
    name VARCHAR(255) NOT NULL,
    status VARCHAR(16) NOT NULL,
    CONSTRAINT ux_score_templates_code_version UNIQUE (code, version)
);

CREATE INDEX IF NOT EXISTS idx_score_templates_code ON score_templates (code);

-- FR-04: at most one ACTIVE template in the whole table (not per-code) —
-- ScoreTemplateService#getActive() resolves a single, unambiguous scheme.
-- Service-layer activate() is the primary guarantee; this is the DB-level
-- safety net for the race two concurrent admin calls could otherwise hit
-- (see ScoreTemplateAdminService#activate Javadoc).
CREATE UNIQUE INDEX IF NOT EXISTS ux_score_templates_single_active
    ON score_templates (status)
    WHERE status = 'ACTIVE';

CREATE TABLE IF NOT EXISTS score_template_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    template_id BIGINT NOT NULL REFERENCES score_templates (id),
    task_type VARCHAR(64) NOT NULL,
    section VARCHAR(16) NOT NULL,
    sequence INTEGER NOT NULL,
    min_count INTEGER NOT NULL,
    max_count INTEGER NOT NULL,
    prep_seconds INTEGER NOT NULL,
    response_seconds INTEGER NOT NULL,
    timing_mode VARCHAR(16) NOT NULL,
    scoring_method VARCHAR(16) NOT NULL,
    overall_weight NUMERIC(5, 2) NOT NULL,
    speaking_weight NUMERIC(5, 2) NOT NULL,
    writing_weight NUMERIC(5, 2) NOT NULL,
    reading_weight NUMERIC(5, 2) NOT NULL,
    listening_weight NUMERIC(5, 2) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_score_template_items_template ON score_template_items (template_id);

-- Seed: APEUni "PTE Content Question Types & Score Information Table V5"
-- (official release), ACTIVE from first boot so ExamSnapshot always has a
-- template to pin (FR-06). Explicit id=1 is safe: this is the very first row
-- this fresh table will ever hold. IMPORTANT: inserting an explicit identity
-- value does NOT advance the GENERATED BY DEFAULT AS IDENTITY sequence —
-- without the setval() below, the very next Hibernate-generated insert would
-- also request id=1 and fail with a duplicate-key violation (caught by
-- applying this migration against a real Postgres and inserting a second row
-- afterward).
--
-- Column conventions (spec.md "Dữ liệu seed V5" + Assumptions):
--   * prep of the 5 audio-prompt Speaking types (RS/RL/ASQ/RTS/SGD) stores
--     preRecordSeconds, not the full dynamic prep (see attempt.SnapshotPinService,
--     Phase 3) — RS/ASQ "No preparation" is conventionally 3s for the beep.
--   * RECOMMENDED rows' response_seconds keep this codebase's EXISTING
--     task-timing.json values (not V5's own recommended figures) per spec —
--     no behavior change for Reading/Listening except WRITE_FROM_DICTATION,
--     which V5 fixes at 120s ("2 minutes per question") vs. the prior 30s.
--   * "<1%" in the source table = 0.50 (MC_READING_SINGLE, HIGHLIGHT_CORRECT_SUMMARY,
--     MC_LISTENING_SINGLE overall weight).
INSERT INTO score_templates (id, public_id, created_at, updated_at, deleted, code, version, name, status)
VALUES (1, gen_random_uuid(), now(), now(), FALSE, 'APEUNI_V5', 1, 'APEUni PTE Score Table V5', 'ACTIVE');

-- Advance the identity sequence past the explicit id=1 above, or the next
-- Hibernate-generated ScoreTemplate insert (e.g. the first cloneToDraft)
-- would also be assigned id=1 and fail on the primary key.
SELECT setval(pg_get_serial_sequence('score_templates', 'id'), 1, true);

INSERT INTO score_template_items (
    public_id, created_at, updated_at, deleted, template_id, task_type, section, sequence,
    min_count, max_count, prep_seconds, response_seconds, timing_mode, scoring_method,
    overall_weight, speaking_weight, writing_weight, reading_weight, listening_weight
) VALUES
(gen_random_uuid(), now(), now(), FALSE, 1, 'READ_ALOUD',                  'SPEAKING',  1,  6, 7,  35, 40,   'FIXED',       'AI_SPEECH', 4,    9,  0,  0,  0),
(gen_random_uuid(), now(), now(), FALSE, 1, 'REPEAT_SENTENCE',             'SPEAKING',  2,  10,12, 3,  15,   'FIXED',       'AI_SPEECH', 7,    16, 0,  0,  17),
(gen_random_uuid(), now(), now(), FALSE, 1, 'DESCRIBE_IMAGE',              'SPEAKING',  3,  5, 6,  25, 40,   'FIXED',       'AI_SPEECH', 15,   31, 0,  0,  0),
(gen_random_uuid(), now(), now(), FALSE, 1, 'RE_TELL_LECTURE',             'SPEAKING',  4,  2, 3,  10, 40,   'FIXED',       'AI_SPEECH', 6,    13, 0,  0,  13),
(gen_random_uuid(), now(), now(), FALSE, 1, 'ANSWER_SHORT_QUESTION',       'SPEAKING',  5,  5, 6,  3,  10,   'FIXED',       'AI_SPEECH', 2,    0,  0,  0,  4),
(gen_random_uuid(), now(), now(), FALSE, 1, 'SUMMARIZE_GROUP_DISCUSSION',  'SPEAKING',  6,  2, 3,  10, 120,  'FIXED',       'AI_SPEECH', 9,    19, 0,  0,  20),
(gen_random_uuid(), now(), now(), FALSE, 1, 'RESPOND_TO_A_SITUATION',      'SPEAKING',  7,  2, 3,  10, 40,   'FIXED',       'AI_SPEECH', 6,    13, 0,  0,  0),
(gen_random_uuid(), now(), now(), FALSE, 1, 'SUMMARIZE_WRITTEN_TEXT',      'WRITING',   8,  2, 2,  0,  600,  'FIXED',       'AI_TEXT',   7,    0,  28, 23, 0),
(gen_random_uuid(), now(), now(), FALSE, 1, 'WRITE_ESSAY',                 'WRITING',   9,  1, 1,  0,  1200, 'FIXED',       'AI_TEXT',   7,    0,  31, 0,  0),
(gen_random_uuid(), now(), now(), FALSE, 1, 'FILL_BLANKS_READING_WRITING', 'READING',   10, 5, 6,  0,  90,   'RECOMMENDED', 'OBJECTIVE', 7,    0,  0,  25, 0),
(gen_random_uuid(), now(), now(), FALSE, 1, 'MC_READING_MULTIPLE',         'READING',   11, 2, 3,  0,  90,   'RECOMMENDED', 'OBJECTIVE', 1,    0,  0,  5,  0),
(gen_random_uuid(), now(), now(), FALSE, 1, 'RE_ORDER_PARAGRAPHS',         'READING',   12, 2, 3,  0,  75,   'RECOMMENDED', 'OBJECTIVE', 3,    0,  0,  9,  0),
(gen_random_uuid(), now(), now(), FALSE, 1, 'FILL_BLANKS_READING',         'READING',   13, 4, 5,  0,  90,   'RECOMMENDED', 'OBJECTIVE', 6,    0,  0,  20, 0),
(gen_random_uuid(), now(), now(), FALSE, 1, 'MC_READING_SINGLE',           'READING',   14, 2, 3,  0,  60,   'RECOMMENDED', 'OBJECTIVE', 0.5,  0,  0,  3,  0),
(gen_random_uuid(), now(), now(), FALSE, 1, 'SUMMARIZE_SPOKEN_TEXT',       'LISTENING', 15, 1, 1,  0,  600,  'FIXED',       'AI_TEXT',   4,    0,  18, 0,  10),
(gen_random_uuid(), now(), now(), FALSE, 1, 'MC_LISTENING_MULTIPLE',       'LISTENING', 16, 2, 3,  0,  20,   'RECOMMENDED', 'OBJECTIVE', 1,    0,  0,  0,  3),
(gen_random_uuid(), now(), now(), FALSE, 1, 'FILL_BLANKS_LISTENING',       'LISTENING', 17, 2, 3,  0,  60,   'RECOMMENDED', 'OBJECTIVE', 3,    0,  0,  0,  8),
(gen_random_uuid(), now(), now(), FALSE, 1, 'HIGHLIGHT_CORRECT_SUMMARY',   'LISTENING', 18, 2, 3,  0,  20,   'RECOMMENDED', 'OBJECTIVE', 0.5,  0,  0,  3,  2),
(gen_random_uuid(), now(), now(), FALSE, 1, 'MC_LISTENING_SINGLE',         'LISTENING', 19, 2, 3,  0,  20,   'RECOMMENDED', 'OBJECTIVE', 0.5,  0,  0,  0,  2),
(gen_random_uuid(), now(), now(), FALSE, 1, 'SELECT_MISSING_WORD',         'LISTENING', 20, 1, 2,  0,  20,   'RECOMMENDED', 'OBJECTIVE', 1,    0,  0,  0,  1),
(gen_random_uuid(), now(), now(), FALSE, 1, 'HIGHLIGHT_INCORRECT_WORDS',   'LISTENING', 21, 2, 3,  0,  30,   'RECOMMENDED', 'OBJECTIVE', 4,    0,  0,  13, 8),
(gen_random_uuid(), now(), now(), FALSE, 1, 'WRITE_FROM_DICTATION',        'LISTENING', 22, 3, 4,  0,  120,  'FIXED',       'OBJECTIVE', 5,    0,  23, 0,  13);
