-- billing module (plans/quang-tenant-commercialization Phase 3).
-- Plan families deliberately share one catalog table; the service validates
-- which family-specific fields may be populated.
-- This is additive and intentionally has no destructive down migration; a
-- rollback requires restoring a database snapshot or a separately reviewed
-- down migration so existing catalog and setting data cannot be lost.
CREATE TABLE IF NOT EXISTS plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    type VARCHAR(32) NOT NULL,
    price NUMERIC(19, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    duration_days INTEGER,
    max_students_per_session INTEGER,
    extra_student_slots INTEGER,
    status VARCHAR(32) NOT NULL,
    CONSTRAINT chk_plans_type CHECK (type IN ('EXAM_PACKAGE', 'STUDENT_CAPACITY')),
    CONSTRAINT chk_plans_status CHECK (status IN ('DRAFT', 'ACTIVE', 'ARCHIVED')),
    CONSTRAINT chk_plans_family_fields CHECK (
        (type = 'EXAM_PACKAGE'
            AND duration_days IS NOT NULL
            AND duration_days > 0
            AND max_students_per_session IS NOT NULL
            AND max_students_per_session > 0
            AND extra_student_slots IS NULL)
        OR
        (type = 'STUDENT_CAPACITY'
            AND duration_days IS NULL
            AND max_students_per_session IS NULL
            AND extra_student_slots IS NOT NULL
            AND extra_student_slots > 0)
    )
);

CREATE INDEX IF NOT EXISTS idx_plans_status ON plans (status);

CREATE TABLE IF NOT EXISTS platform_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    setting_key VARCHAR(100) NOT NULL UNIQUE,
    value VARCHAR(255) NOT NULL,
    description VARCHAR(255)
);

INSERT INTO platform_settings (
        public_id, created_at, updated_at, deleted, setting_key, value, description)
SELECT '00000000-0000-0000-0000-000000000001', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,
       FALSE, 'free_student_limit', '50',
       'Free student limit granted when a tenant application is approved'
WHERE NOT EXISTS (
    SELECT 1 FROM platform_settings WHERE setting_key = 'free_student_limit'
);

INSERT INTO platform_settings (
        public_id, created_at, updated_at, deleted, setting_key, value, description)
SELECT '00000000-0000-0000-0000-000000000002', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,
       FALSE, 'suspension_default_days', '0',
       'Default suspension duration; zero means no automatic expiry'
WHERE NOT EXISTS (
    SELECT 1 FROM platform_settings WHERE setting_key = 'suspension_default_days'
);
