-- session module (plans/score-template-exam-generation, Plan B / Phase 4).
-- Remembers which enrollment.StudentClass Classes (referenced by public_id,
-- never a cross-module FK) have been assigned to a session, so a re-assign
-- knows whether to insert a new assignment row or just re-run bulk enroll.

CREATE TABLE session_class_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    session_id BIGINT NOT NULL REFERENCES exam_sessions (id),
    tenant_id UUID NOT NULL,
    class_public_id UUID NOT NULL,
    CONSTRAINT ux_session_class_assignments_session_class UNIQUE (session_id, class_public_id)
);

CREATE INDEX idx_session_class_assignments_session ON session_class_assignments (session_id);
