-- billing module (plans/quang-tenant-commercialization Phase 2).
-- TenantApplication is deliberately its own table, not a status on `tenants`
-- — the tenant does not exist until an application is approved (ADR-006).

CREATE TABLE IF NOT EXISTS tenant_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    org_name VARCHAR(255) NOT NULL,
    org_type VARCHAR(255) NOT NULL,
    requested_code VARCHAR(32) NOT NULL,
    contact_email VARCHAR(255) NOT NULL,
    contact_phone VARCHAR(255),
    tax_code VARCHAR(255),
    status VARCHAR(32) NOT NULL,
    reviewed_by UUID,
    reviewed_at TIMESTAMP WITH TIME ZONE,
    reject_reason VARCHAR(500)
);

-- Reserves a requested_code the moment an application is submitted, not when
-- it's approved. Partial (WHERE status = 'PENDING') so a REJECTED or already
-- APPROVED application never blocks someone else from reusing that code.
CREATE UNIQUE INDEX IF NOT EXISTS uq_application_code_active
    ON tenant_applications (requested_code)
    WHERE status = 'PENDING';
