-- assessment template catalog (commercialization Phase 09).
-- Platform-owned templates keep tenant_id null; sections and slots form one
-- replaceable draft aggregate and are copied when an active template is cloned.

CREATE TABLE IF NOT EXISTS exam_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    tenant_id UUID,
    status VARCHAR(16) NOT NULL,
    CONSTRAINT exam_templates_platform_owned CHECK (tenant_id IS NULL)
);

CREATE INDEX IF NOT EXISTS idx_exam_templates_status ON exam_templates (status);

CREATE TABLE IF NOT EXISTS template_sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    template_id BIGINT NOT NULL REFERENCES exam_templates (id),
    section VARCHAR(16) NOT NULL,
    weight_percent INTEGER NOT NULL,
    order_index INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_template_sections_template ON template_sections (template_id);

CREATE TABLE IF NOT EXISTS template_slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    template_section_id BIGINT NOT NULL REFERENCES template_sections (id),
    task_type VARCHAR(64) NOT NULL,
    question_count INTEGER NOT NULL,
    order_index INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_template_slots_section ON template_slots (template_section_id);
