-- Template provenance and immutable section weights for generated snapshots.

ALTER TABLE exam_snapshots ADD COLUMN IF NOT EXISTS template_public_id UUID;
ALTER TABLE exam_snapshots ADD COLUMN IF NOT EXISTS random_seed BIGINT NOT NULL DEFAULT 0;
ALTER TABLE attempt_reports ADD COLUMN IF NOT EXISTS snapshot_public_id UUID;

ALTER TABLE questions
    ADD CONSTRAINT questions_platform_owned CHECK (tenant_id IS NULL);

CREATE TABLE IF NOT EXISTS snapshot_section_weights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    snapshot_id BIGINT NOT NULL REFERENCES exam_snapshots (id),
    section VARCHAR(16) NOT NULL,
    weight_percent INTEGER NOT NULL,
    order_index INTEGER NOT NULL,
    CONSTRAINT uq_snapshot_section_weights_snapshot_section UNIQUE (snapshot_id, section)
);

CREATE INDEX IF NOT EXISTS idx_snapshot_section_weights_snapshot
    ON snapshot_section_weights (snapshot_id);
