-- Phase 4: one independent Subscription instance per EXAM_PACKAGE activation.
-- tenant_id and plan_id are scalar public IDs intentionally; module boundaries
-- are enforced in code, not with cross-module JPA associations.

CREATE TABLE IF NOT EXISTS subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    tenant_id UUID NOT NULL,
    plan_id UUID NOT NULL,
    license_key VARCHAR(32) NOT NULL UNIQUE,
    starts_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    max_students_per_session INTEGER NOT NULL,
    status VARCHAR(16) NOT NULL,
    activation_source VARCHAR(16) NOT NULL,
    CONSTRAINT chk_subscriptions_dates CHECK (expires_at > starts_at),
    CONSTRAINT chk_subscriptions_cap CHECK (max_students_per_session > 0),
    CONSTRAINT chk_subscriptions_status CHECK (status IN ('ACTIVE', 'EXPIRED', 'CANCELLED')),
    CONSTRAINT chk_subscriptions_source CHECK (activation_source IN ('PAYMENT', 'LICENSE_CODE'))
);

CREATE INDEX IF NOT EXISTS idx_subscriptions_tenant_status
    ON subscriptions (tenant_id, status);
