-- Phase 5: PayOS order reservations and append-only webhook receipts.
-- There is intentionally no down migration in this repository. Rollback of a
-- deployed schema must be an explicitly reviewed operational migration.

CREATE SEQUENCE IF NOT EXISTS order_code_seq
    AS BIGINT
    START WITH 1000000000
    INCREMENT BY 1
    MINVALUE 1000000000
    NO MAXVALUE
    CACHE 1;

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    tenant_id UUID NOT NULL,
    plan_id UUID NOT NULL,
    order_code BIGINT NOT NULL UNIQUE,
    amount NUMERIC(19, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    status VARCHAR(16) NOT NULL,
    payment_link_url VARCHAR(512),
    paid_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT chk_orders_amount CHECK (amount > 0),
    CONSTRAINT chk_orders_status CHECK (status IN ('PENDING', 'PAID', 'CANCELLED', 'EXPIRED'))
);

CREATE INDEX IF NOT EXISTS idx_orders_tenant_created
    ON orders (tenant_id, created_at);

CREATE INDEX IF NOT EXISTS idx_orders_status_created
    ON orders (status, created_at);

CREATE UNIQUE INDEX IF NOT EXISTS ux_orders_pending_tenant_plan
    ON orders (tenant_id, plan_id)
    WHERE status = 'PENDING' AND deleted = FALSE;

CREATE TABLE IF NOT EXISTS payment_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    order_code BIGINT,
    raw_payload TEXT NOT NULL,
    signature_valid BOOLEAN NOT NULL,
    received_at TIMESTAMP WITH TIME ZONE NOT NULL,
    processed BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_payment_transactions_order_code
    ON payment_transactions (order_code);

CREATE INDEX IF NOT EXISTS idx_payment_transactions_received_at
    ON payment_transactions (received_at);
