-- Phase 6: individually issued bearer activation codes.
-- Forward-only business-data migration. Rollback requires an operator-approved
-- backup/restore because redeemed-code and subscription links are audit data.

CREATE TABLE IF NOT EXISTS license_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    code VARCHAR(32) NOT NULL UNIQUE,
    plan_id UUID NOT NULL,
    status VARCHAR(16) NOT NULL,
    issued_by UUID NOT NULL,
    issued_at TIMESTAMP WITH TIME ZONE NOT NULL,
    code_expires_at TIMESTAMP WITH TIME ZONE,
    redeemed_by_tenant_id UUID,
    redeemed_at TIMESTAMP WITH TIME ZONE,
    subscription_id UUID UNIQUE,
    revoke_reason VARCHAR(255),
    CONSTRAINT chk_license_codes_status CHECK (status IN ('ISSUED', 'REDEEMED', 'REVOKED', 'EXPIRED')),
    CONSTRAINT chk_license_codes_redeem_fields CHECK (
        (status = 'ISSUED' AND redeemed_by_tenant_id IS NULL AND redeemed_at IS NULL)
        OR (status IN ('REDEEMED', 'REVOKED', 'EXPIRED'))
    )
);

CREATE INDEX IF NOT EXISTS idx_license_codes_status_expiry
    ON license_codes (status, code_expires_at);
