-- identity module (plans/modular-monolith Phase 02).
--
-- Hand-written to match what Hibernate derives from User/LoginHash/RefreshToken
-- (all extending shared.domain.BaseEntity) — NOT copied from services/iam,
-- which never had a Flyway migration of its own (ddl-auto: update there). The
-- monolith uses ddl-auto: validate (Phase 01), so this migration is the actual
-- source of truth for the schema, checked against the entities at startup.

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    email VARCHAR(255) NOT NULL UNIQUE,
    full_name VARCHAR(255) NOT NULL,
    tenant_id UUID,
    status VARCHAR(32) NOT NULL,
    student_code VARCHAR(255),
    class_name VARCHAR(255),
    phone VARCHAR(255),
    date_of_birth DATE
);

CREATE INDEX IF NOT EXISTS idx_users_tenant ON users (tenant_id);

-- @ElementCollection(Set<Role>) — no synthetic PK, matches Hibernate's default
-- shape for a Set-valued element collection with no explicit @OrderColumn.
CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL REFERENCES users (id),
    role VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS login_hashes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    user_id BIGINT NOT NULL UNIQUE,
    hash VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_refresh_user ON refresh_tokens (user_id);
