-- Persisted question-type catalog. Question rows keep the stable PTE code in
-- pte_task_type, while authoring requirements and presentation metadata are
-- managed here and fetched by clients.
CREATE TABLE IF NOT EXISTS question_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    code VARCHAR(64) NOT NULL UNIQUE,
    display_name VARCHAR(128) NOT NULL,
    short_name VARCHAR(32) NOT NULL,
    section VARCHAR(16) NOT NULL,
    scored BOOLEAN NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INTEGER NOT NULL,
    requires_audio_prompt BOOLEAN NOT NULL DEFAULT FALSE,
    requires_image_prompt BOOLEAN NOT NULL DEFAULT FALSE,
    requires_prompt_text BOOLEAN NOT NULL DEFAULT FALSE,
    requires_options BOOLEAN NOT NULL DEFAULT FALSE,
    requires_correct_answer BOOLEAN NOT NULL DEFAULT FALSE,
    requires_word_count BOOLEAN NOT NULL DEFAULT FALSE,
    requires_single_correct_option BOOLEAN NOT NULL DEFAULT FALSE,
    uses_option_order_as_correct_position BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_question_types_active_order
    ON question_types (active, display_order);

-- Question types are intentionally not seeded here. Platform admins import
-- the existing score-template data through the vendor UI, then complete the
-- catalog metadata there. NOT VALID keeps legacy question rows migratable
-- while enforcing the catalog for all newly authored questions.
ALTER TABLE questions
    ADD CONSTRAINT fk_questions_question_type
    FOREIGN KEY (pte_task_type) REFERENCES question_types (code) NOT VALID;
