-- Tenancy and shared audit data for the modular monolith (Phase 03).
-- This is an additive migration. Automatic rollback is intentionally omitted:
-- dropping these tables would destroy tenant data; rollback requires a database
-- snapshot or a separately reviewed down migration.

CREATE TABLE IF NOT EXISTS tenants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    -- plans/quang-tenant-commercialization Phase 1: chosen by the org when it
    -- submits its application (Phase 2), immutable after approval. Used as
    -- the prefix for every student username this tenant's roster import
    -- generates ({tenant.code}.{random}).
    code VARCHAR(32) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL UNIQUE,
    organization_type VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL,
    package_name VARCHAR(255) NOT NULL,
    student_limit INTEGER NOT NULL,
    logo_url VARCHAR(255),
    primary_color VARCHAR(255),
    version BIGINT
);

CREATE TABLE IF NOT EXISTS organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    tenant_id BIGINT NOT NULL REFERENCES tenants (id),
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255),
    facility_type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_organizations_tenant ON organizations (tenant_id);

CREATE TABLE IF NOT EXISTS quota_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    tenant_id BIGINT NOT NULL REFERENCES tenants (id),
    package_name VARCHAR(255) NOT NULL,
    amount INTEGER NOT NULL,
    action_type VARCHAR(32) NOT NULL,
    actor_user_id UUID NOT NULL,
    note VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_quota_transactions_tenant ON quota_transactions (tenant_id);

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    tenant_id UUID NOT NULL,
    actor_user_id UUID NOT NULL,
    aggregate_type VARCHAR(255) NOT NULL,
    aggregate_id VARCHAR(255) NOT NULL,
    action VARCHAR(255) NOT NULL,
    summary VARCHAR(500) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_tenant ON audit_logs (tenant_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_tenant_aggregate_type
    ON audit_logs (tenant_id, aggregate_type);
