ALTER TABLE exam_sessions
    ALTER COLUMN snapshot_public_id DROP NOT NULL,
    ADD COLUMN IF NOT EXISTS template_public_id UUID,
    ADD COLUMN IF NOT EXISTS template_version INTEGER,
    ADD COLUMN IF NOT EXISTS exam_mode VARCHAR(16),
    ADD COLUMN IF NOT EXISTS form_mode VARCHAR(32),
    ADD COLUMN IF NOT EXISTS reuse_policy VARCHAR(40),
    ADD COLUMN IF NOT EXISTS series_key VARCHAR(128),
    ADD COLUMN IF NOT EXISTS generation_job_public_id UUID,
    ADD COLUMN IF NOT EXISTS draft_version BIGINT NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_sessions_tenant_series ON exam_sessions (tenant_id, series_key);

ALTER TABLE exam_sessions DROP CONSTRAINT IF EXISTS no_overlap_per_subscription;
ALTER TABLE exam_sessions ADD CONSTRAINT no_overlap_per_subscription
    EXCLUDE USING gist (
        subscription_id WITH =,
        tstzrange(opens_at, closes_at) WITH &&
    ) WHERE (status IN ('SCHEDULED', 'OPEN'));

CREATE TABLE IF NOT EXISTS exam_audience_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    session_id BIGINT NOT NULL REFERENCES exam_sessions (id),
    tenant_id UUID NOT NULL,
    source_type VARCHAR(16) NOT NULL,
    source_public_id UUID NOT NULL,
    created_by UUID,
    UNIQUE (session_id, source_type, source_public_id)
);

CREATE INDEX IF NOT EXISTS idx_exam_audience_sources_session ON exam_audience_sources (session_id);

CREATE TABLE IF NOT EXISTS exam_audience_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    session_id BIGINT NOT NULL REFERENCES exam_sessions (id),
    tenant_id UUID NOT NULL,
    student_public_id UUID NOT NULL,
    status VARCHAR(16) NOT NULL,
    reason VARCHAR(32),
    source_summary VARCHAR(1000),
    prior_session_public_id UUID,
    prior_session_name VARCHAR(255),
    prior_status VARCHAR(16),
    published_at TIMESTAMP WITH TIME ZONE,
    UNIQUE (session_id, student_public_id)
);

CREATE INDEX IF NOT EXISTS idx_exam_audience_members_session_status
    ON exam_audience_members (session_id, status);

CREATE TABLE IF NOT EXISTS exam_generation_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    session_id BIGINT NOT NULL REFERENCES exam_sessions (id),
    tenant_id UUID NOT NULL,
    status VARCHAR(16) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    algorithm_version VARCHAR(32) NOT NULL,
    base_seed BIGINT NOT NULL,
    forms_total INTEGER NOT NULL DEFAULT 0,
    forms_completed INTEGER NOT NULL DEFAULT 0,
    last_error TEXT,
    UNIQUE (session_id, idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_exam_generation_jobs_session ON exam_generation_jobs (session_id, status);

CREATE TABLE IF NOT EXISTS exam_forms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    session_id BIGINT NOT NULL REFERENCES exam_sessions (id),
    snapshot_public_id UUID NOT NULL,
    form_index INTEGER NOT NULL,
    form_seed BIGINT NOT NULL,
    algorithm_version VARCHAR(32) NOT NULL,
    pool_policy_fingerprint VARCHAR(128) NOT NULL,
    UNIQUE (session_id, form_index)
);

CREATE TABLE IF NOT EXISTS form_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    session_id BIGINT NOT NULL REFERENCES exam_sessions (id),
    form_id BIGINT NOT NULL REFERENCES exam_forms (id),
    student_public_id UUID NOT NULL,
    UNIQUE (session_id, student_public_id)
);

CREATE INDEX IF NOT EXISTS idx_form_assignments_session ON form_assignments (session_id);
