-- Immutable runtime profile contract. Values are semantic allowlist keys; no
-- executable implementation detail is persisted.
CREATE TABLE IF NOT EXISTS task_runtime_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    task_type_code VARCHAR(64) NOT NULL,
    profile_key VARCHAR(96) NOT NULL,
    profile_version INTEGER NOT NULL,
    behavior_key VARCHAR(64) NOT NULL,
    renderer_key VARCHAR(96) NOT NULL,
    answer_schema_version INTEGER NOT NULL,
    scoring_profile_key VARCHAR(64) NOT NULL,
    scoring_profile_version INTEGER NOT NULL,
    required_client_capabilities VARCHAR(512) NOT NULL,
    status VARCHAR(16) NOT NULL,
    CONSTRAINT ux_task_runtime_profiles_task_version UNIQUE (task_type_code, profile_version)
);

CREATE INDEX IF NOT EXISTS idx_task_runtime_profiles_task_status
    ON task_runtime_profiles (task_type_code, status);

ALTER TABLE score_template_items
    ADD COLUMN IF NOT EXISTS runtime_profile_key VARCHAR(96),
    ADD COLUMN IF NOT EXISTS runtime_profile_version INTEGER,
    ADD COLUMN IF NOT EXISTS runtime_behavior_key VARCHAR(64),
    ADD COLUMN IF NOT EXISTS runtime_renderer_key VARCHAR(96),
    ADD COLUMN IF NOT EXISTS runtime_answer_schema_version INTEGER,
    ADD COLUMN IF NOT EXISTS runtime_scoring_profile_key VARCHAR(64),
    ADD COLUMN IF NOT EXISTS runtime_scoring_profile_version INTEGER,
    ADD COLUMN IF NOT EXISTS runtime_required_client_capabilities VARCHAR(512),
    ADD COLUMN IF NOT EXISTS runtime_profile_status VARCHAR(16);

-- The registry in TaskRuntimeProfileRegistry.java is the executable allowlist;
-- these rows are its persisted, versioned data contract.
INSERT INTO task_runtime_profiles (
    public_id, created_at, updated_at, deleted, task_type_code, profile_key,
    profile_version, behavior_key, renderer_key, answer_schema_version,
    scoring_profile_key, scoring_profile_version, required_client_capabilities, status
) VALUES
    (gen_random_uuid(), now(), now(), FALSE, 'PERSONAL_INTRODUCTION', 'PTE.PERSONAL_INTRODUCTION', 1, 'PERSONAL_INTRODUCTION', 'PERSONAL_INTRODUCTION_V1', 1, 'UNSCORED', 1, 'AUDIO_RECORDING', 'ACTIVE'),
    (gen_random_uuid(), now(), now(), FALSE, 'READ_ALOUD', 'PTE.READ_ALOUD', 1, 'RECORD_RESPONSE', 'READ_ALOUD_V1', 1, 'AI_SPEECH', 1, 'AUDIO_RECORDING', 'ACTIVE'),
    (gen_random_uuid(), now(), now(), FALSE, 'REPEAT_SENTENCE', 'PTE.REPEAT_SENTENCE', 1, 'RECORD_RESPONSE', 'REPEAT_SENTENCE_V1', 1, 'AI_SPEECH', 1, 'AUDIO_PLAYBACK,AUDIO_RECORDING', 'ACTIVE'),
    (gen_random_uuid(), now(), now(), FALSE, 'DESCRIBE_IMAGE', 'PTE.DESCRIBE_IMAGE', 1, 'RECORD_RESPONSE', 'DESCRIBE_IMAGE_V1', 1, 'AI_SPEECH', 1, 'IMAGE_DISPLAY,AUDIO_RECORDING', 'ACTIVE'),
    (gen_random_uuid(), now(), now(), FALSE, 'RE_TELL_LECTURE', 'PTE.RE_TELL_LECTURE', 1, 'RECORD_RESPONSE', 'RE_TELL_LECTURE_V1', 1, 'AI_SPEECH', 1, 'AUDIO_PLAYBACK,AUDIO_RECORDING', 'ACTIVE'),
    (gen_random_uuid(), now(), now(), FALSE, 'ANSWER_SHORT_QUESTION', 'PTE.ANSWER_SHORT_QUESTION', 1, 'RECORD_RESPONSE', 'ANSWER_SHORT_QUESTION_V1', 1, 'AI_SPEECH', 1, 'AUDIO_PLAYBACK,AUDIO_RECORDING', 'ACTIVE'),
    (gen_random_uuid(), now(), now(), FALSE, 'RESPOND_TO_A_SITUATION', 'PTE.RESPOND_TO_A_SITUATION', 1, 'RECORD_RESPONSE', 'RESPOND_TO_A_SITUATION_V1', 1, 'AI_SPEECH', 1, 'AUDIO_PLAYBACK,AUDIO_RECORDING', 'ACTIVE'),
    (gen_random_uuid(), now(), now(), FALSE, 'SUMMARIZE_GROUP_DISCUSSION', 'PTE.SUMMARIZE_GROUP_DISCUSSION', 1, 'RECORD_RESPONSE', 'SUMMARIZE_GROUP_DISCUSSION_V1', 1, 'AI_SPEECH', 1, 'AUDIO_PLAYBACK,AUDIO_RECORDING', 'ACTIVE'),
    (gen_random_uuid(), now(), now(), FALSE, 'SUMMARIZE_WRITTEN_TEXT', 'PTE.SUMMARIZE_WRITTEN_TEXT', 1, 'TEXT_RESPONSE', 'SUMMARIZE_WRITTEN_TEXT_V1', 1, 'AI_TEXT', 1, 'TEXT_INPUT', 'ACTIVE'),
    (gen_random_uuid(), now(), now(), FALSE, 'WRITE_ESSAY', 'PTE.WRITE_ESSAY', 1, 'TEXT_RESPONSE', 'WRITE_ESSAY_V1', 1, 'AI_TEXT', 1, 'TEXT_INPUT', 'ACTIVE'),
    (gen_random_uuid(), now(), now(), FALSE, 'MC_READING_SINGLE', 'PTE.MC_READING_SINGLE', 1, 'SELECT_OPTION', 'MC_READING_SINGLE_V1', 1, 'OBJECTIVE', 1, 'OPTION_SELECTION', 'ACTIVE'),
    (gen_random_uuid(), now(), now(), FALSE, 'MC_READING_MULTIPLE', 'PTE.MC_READING_MULTIPLE', 1, 'SELECT_OPTIONS', 'MC_READING_MULTIPLE_V1', 1, 'OBJECTIVE', 1, 'OPTION_SELECTION', 'ACTIVE'),
    (gen_random_uuid(), now(), now(), FALSE, 'RE_ORDER_PARAGRAPHS', 'PTE.RE_ORDER_PARAGRAPHS', 1, 'ORDER_OPTIONS', 'RE_ORDER_PARAGRAPHS_V1', 1, 'OBJECTIVE', 1, 'DRAG_AND_DROP', 'ACTIVE'),
    (gen_random_uuid(), now(), now(), FALSE, 'FILL_IN_THE_BLANKS_DRAG_AND_DROP', 'PTE.FILL_IN_THE_BLANKS_DRAG_AND_DROP', 1, 'FILL_BLANKS', 'FILL_IN_THE_BLANKS_DRAG_AND_DROP_V1', 1, 'OBJECTIVE', 1, 'DRAG_AND_DROP', 'ACTIVE'),
    (gen_random_uuid(), now(), now(), FALSE, 'FILL_IN_THE_BLANKS_DROPDOWN', 'PTE.FILL_IN_THE_BLANKS_DROPDOWN', 1, 'FILL_BLANKS', 'FILL_IN_THE_BLANKS_DROPDOWN_V1', 1, 'OBJECTIVE', 1, 'DROPDOWN_SELECTION', 'ACTIVE'),
    (gen_random_uuid(), now(), now(), FALSE, 'SUMMARIZE_SPOKEN_TEXT', 'PTE.SUMMARIZE_SPOKEN_TEXT', 1, 'TEXT_RESPONSE', 'SUMMARIZE_SPOKEN_TEXT_V1', 1, 'AI_TEXT', 1, 'AUDIO_PLAYBACK,TEXT_INPUT', 'ACTIVE'),
    (gen_random_uuid(), now(), now(), FALSE, 'MC_LISTENING_SINGLE', 'PTE.MC_LISTENING_SINGLE', 1, 'SELECT_OPTION', 'MC_LISTENING_SINGLE_V1', 1, 'OBJECTIVE', 1, 'AUDIO_PLAYBACK,OPTION_SELECTION', 'ACTIVE'),
    (gen_random_uuid(), now(), now(), FALSE, 'MC_LISTENING_MULTIPLE', 'PTE.MC_LISTENING_MULTIPLE', 1, 'SELECT_OPTIONS', 'MC_LISTENING_MULTIPLE_V1', 1, 'OBJECTIVE', 1, 'AUDIO_PLAYBACK,OPTION_SELECTION', 'ACTIVE'),
    (gen_random_uuid(), now(), now(), FALSE, 'FILL_IN_THE_BLANKS_TYPE_IN', 'PTE.FILL_IN_THE_BLANKS_TYPE_IN', 1, 'TEXT_RESPONSE', 'FILL_IN_THE_BLANKS_TYPE_IN_V1', 1, 'OBJECTIVE', 1, 'AUDIO_PLAYBACK,TEXT_INPUT', 'ACTIVE'),
    (gen_random_uuid(), now(), now(), FALSE, 'HIGHLIGHT_CORRECT_SUMMARY', 'PTE.HIGHLIGHT_CORRECT_SUMMARY', 1, 'HIGHLIGHT_OPTIONS', 'HIGHLIGHT_CORRECT_SUMMARY_V1', 1, 'OBJECTIVE', 1, 'AUDIO_PLAYBACK,HIGHLIGHT_SELECTION', 'ACTIVE'),
    (gen_random_uuid(), now(), now(), FALSE, 'SELECT_MISSING_WORD', 'PTE.SELECT_MISSING_WORD', 1, 'SELECT_OPTION', 'SELECT_MISSING_WORD_V1', 1, 'OBJECTIVE', 1, 'AUDIO_PLAYBACK,OPTION_SELECTION', 'ACTIVE'),
    (gen_random_uuid(), now(), now(), FALSE, 'HIGHLIGHT_INCORRECT_WORDS', 'PTE.HIGHLIGHT_INCORRECT_WORDS', 1, 'HIGHLIGHT_TEXT', 'HIGHLIGHT_INCORRECT_WORDS_V1', 1, 'OBJECTIVE', 1, 'AUDIO_PLAYBACK,HIGHLIGHT_SELECTION', 'ACTIVE'),
    (gen_random_uuid(), now(), now(), FALSE, 'WRITE_FROM_DICTATION', 'PTE.WRITE_FROM_DICTATION', 1, 'TEXT_RESPONSE', 'WRITE_FROM_DICTATION_V1', 1, 'OBJECTIVE', 1, 'AUDIO_PLAYBACK,TEXT_INPUT', 'ACTIVE')
ON CONFLICT (task_type_code, profile_version) DO NOTHING;

-- Pin the clean seeded template and any legacy standard template items once;
-- existing explicit pins are never overwritten.
UPDATE score_template_items item
   SET runtime_profile_key = profile.profile_key,
       runtime_profile_version = profile.profile_version,
       runtime_behavior_key = profile.behavior_key,
       runtime_renderer_key = profile.renderer_key,
       runtime_answer_schema_version = profile.answer_schema_version,
       runtime_scoring_profile_key = profile.scoring_profile_key,
       runtime_scoring_profile_version = profile.scoring_profile_version,
       runtime_required_client_capabilities = profile.required_client_capabilities,
       runtime_profile_status = profile.status
  FROM task_runtime_profiles profile
 WHERE item.task_type = profile.task_type_code
   AND item.runtime_profile_version IS NULL;
