-- Enrollment hierarchy and assignments for the modular monolith (Phase 03).
-- This is an additive migration. Automatic rollback is intentionally omitted:
-- dropping these tables would destroy enrollment data; rollback requires a
-- database snapshot or a separately reviewed down migration.

-- Identity owns this read-only surface. Enrollment may join it, but never
-- reaches the identity tables directly. It keeps the roster on one SQL query
-- while preserving the module boundary at the database object level.
CREATE OR REPLACE VIEW identity_student_directory AS
SELECT u.id,
       u.public_id,
       u.email,
       u.full_name,
       u.student_code,
       u.phone,
       u.status,
       u.created_at,
       u.tenant_id,
       u.deleted
FROM users u
JOIN user_roles ur ON ur.user_id = u.id AND ur.role = 'STUDENT';

-- Supports the identity-owned view's role join when the tenant roster is large.
CREATE INDEX IF NOT EXISTS idx_user_roles_user_role ON user_roles (user_id, role);

CREATE TABLE IF NOT EXISTS programs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL REFERENCES organizations (id),
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    start_date DATE,
    end_date DATE,
    status VARCHAR(32) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_programs_organization ON programs (organization_id);

CREATE TABLE IF NOT EXISTS student_classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    program_id BIGINT NOT NULL REFERENCES programs (id),
    name VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_student_classes_program ON student_classes (program_id);

CREATE TABLE IF NOT EXISTS class_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    student_class_id BIGINT NOT NULL REFERENCES student_classes (id),
    student_public_id UUID NOT NULL UNIQUE,
    tenant_id UUID NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_class_memberships_class ON class_memberships (student_class_id);
CREATE INDEX IF NOT EXISTS idx_class_memberships_tenant ON class_memberships (tenant_id);

CREATE TABLE IF NOT EXISTS lecturer_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    student_class_id BIGINT NOT NULL REFERENCES student_classes (id),
    assignee_public_id UUID NOT NULL,
    tenant_id UUID NOT NULL,
    CONSTRAINT uk_lecturer_assignment_class_assignee
        UNIQUE (student_class_id, assignee_public_id)
);

CREATE INDEX IF NOT EXISTS idx_lecturer_assignments_class ON lecturer_assignments (student_class_id);

CREATE TABLE IF NOT EXISTS program_coordinator_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    program_id BIGINT NOT NULL REFERENCES programs (id),
    assignee_public_id UUID NOT NULL,
    tenant_id UUID NOT NULL,
    CONSTRAINT uk_coordinator_assignment_program_assignee
        UNIQUE (program_id, assignee_public_id)
);

CREATE INDEX IF NOT EXISTS idx_coordinator_assignments_program ON program_coordinator_assignments (program_id);
