-- Release-owned semantic runtime contracts. A task type points at a contract;
-- the row contains no executable class, script, formula or client source path.
CREATE TABLE IF NOT EXISTS task_runtime_contracts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    screen_key VARCHAR(96) NOT NULL,
    contract_version INTEGER NOT NULL,
    profile_key VARCHAR(96) NOT NULL,
    profile_version INTEGER NOT NULL,
    behavior_key VARCHAR(64) NOT NULL,
    renderer_key VARCHAR(96) NOT NULL,
    answer_schema_version INTEGER NOT NULL,
    scoring_profile_key VARCHAR(64) NOT NULL,
    scoring_profile_version INTEGER NOT NULL,
    scoring_mode VARCHAR(16) NOT NULL,
    required_client_capabilities TEXT[] NOT NULL DEFAULT '{}',
    min_supported_app_version VARCHAR(32),
    authoring_contract_key VARCHAR(96) NOT NULL,
    authoring_contract_version INTEGER NOT NULL,
    requires_audio_prompt BOOLEAN NOT NULL DEFAULT FALSE,
    requires_image_prompt BOOLEAN NOT NULL DEFAULT FALSE,
    requires_prompt_text BOOLEAN NOT NULL DEFAULT FALSE,
    requires_options BOOLEAN NOT NULL DEFAULT FALSE,
    requires_correct_answer BOOLEAN NOT NULL DEFAULT FALSE,
    requires_word_count BOOLEAN NOT NULL DEFAULT FALSE,
    requires_single_correct_option BOOLEAN NOT NULL DEFAULT FALSE,
    uses_option_order_as_correct_position BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT ux_task_runtime_contract_screen_version
        UNIQUE (screen_key, contract_version)
);

CREATE INDEX IF NOT EXISTS idx_task_runtime_contracts_status
    ON task_runtime_contracts (status, screen_key);

-- Seed the canonical registry from the existing code-owned profile projection.
-- Existing standard rows become reusable screen contracts; two future logical
-- task keys may reference one row without changing this uniqueness constraint.
INSERT INTO task_runtime_contracts (
    public_id, created_at, updated_at, deleted, screen_key, contract_version,
    profile_key, profile_version, behavior_key, renderer_key,
    answer_schema_version, scoring_profile_key, scoring_profile_version,
    scoring_mode, required_client_capabilities, min_supported_app_version,
    authoring_contract_key, authoring_contract_version,
    requires_audio_prompt, requires_image_prompt, requires_prompt_text,
    requires_options, requires_correct_answer, requires_word_count,
    requires_single_correct_option, uses_option_order_as_correct_position, status
)
SELECT gen_random_uuid(), now(), now(), FALSE,
       profile.renderer_key, profile.profile_version,
       profile.profile_key, profile.profile_version, profile.behavior_key,
       profile.renderer_key, profile.answer_schema_version,
       profile.scoring_profile_key, profile.scoring_profile_version,
       CASE WHEN definition.scored THEN 'SCORED' ELSE 'NONE' END,
       CASE WHEN profile.required_client_capabilities IS NULL
            OR profile.required_client_capabilities = '' THEN '{}'
            ELSE string_to_array(profile.required_client_capabilities, ',') END,
       '1.0.0', 'PTE.' || definition.code || '_AUTHORING', 1,
       definition.requires_audio_prompt, definition.requires_image_prompt,
       definition.requires_prompt_text, definition.requires_options,
       definition.requires_correct_answer, definition.requires_word_count,
       definition.requires_single_correct_option,
       definition.uses_option_order_as_correct_position, 'ACTIVE'
  FROM task_runtime_profiles profile
  JOIN question_types definition ON definition.code = profile.task_type_code
 ON CONFLICT (screen_key, contract_version) DO NOTHING;

UPDATE question_types definition
   SET screen_key = contract.screen_key,
       runtime_profile_key = contract.profile_key,
       runtime_profile_version = contract.profile_version,
       runtime_behavior_key = contract.behavior_key,
       runtime_renderer_key = contract.renderer_key,
       runtime_answer_schema_version = contract.answer_schema_version,
       runtime_scoring_profile_key = contract.scoring_profile_key,
       runtime_scoring_profile_version = contract.scoring_profile_version,
       runtime_scoring_mode = contract.scoring_mode,
       runtime_required_capabilities = contract.required_client_capabilities,
       runtime_min_app_version = contract.min_supported_app_version,
       authoring_contract_key = contract.authoring_contract_key,
       authoring_contract_version = contract.authoring_contract_version
  FROM task_runtime_profiles profile
  JOIN task_runtime_contracts contract
    ON contract.screen_key = profile.renderer_key
   AND contract.contract_version = profile.profile_version
 WHERE definition.code = profile.task_type_code;
