-- Append-only publication evidence. Retiring/unpublishing a template never
-- deletes this history, so runtime fields remain locked forever after use.
CREATE TABLE IF NOT EXISTS task_type_publication_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    task_type_key VARCHAR(64) NOT NULL,
    template_public_id UUID NOT NULL,
    template_version_public_id UUID NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE NOT NULL,
    actor_public_id UUID,
    audit_reference VARCHAR(128),
    CONSTRAINT ux_task_type_publication_usage_template_task
        UNIQUE (task_type_key, template_version_public_id)
);

CREATE INDEX IF NOT EXISTS idx_task_type_publication_usage_task
    ON task_type_publication_usage (task_type_key);
