-- Add scoring provenance and the session-scoped Examiner/review foundation.
-- Legacy scores remain intact; nullable provenance deliberately means unknown.

ALTER TABLE scoring_answers
    ADD COLUMN ai_provider_category VARCHAR(16),
    ADD COLUMN ai_provider VARCHAR(64),
    ADD COLUMN ai_model VARCHAR(160),
    ADD COLUMN ai_provider_version VARCHAR(100),
    ADD COLUMN selected_score_source VARCHAR(16),
    ADD COLUMN selected_score_source_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN selected_score_source_by_public_id UUID,
    ADD COLUMN lock_version BIGINT NOT NULL DEFAULT 0,
    ADD CONSTRAINT ck_scoring_answers_ai_provider_category
        CHECK (ai_provider_category IS NULL OR ai_provider_category IN ('REAL', 'STUB')),
    ADD CONSTRAINT ck_scoring_answers_selected_score_source
        CHECK (selected_score_source IS NULL OR selected_score_source IN ('AI', 'EXAMINER')),
    ADD CONSTRAINT ck_scoring_answers_ai_provenance_complete
        CHECK ((ai_provider_category IS NULL AND ai_provider IS NULL AND ai_model IS NULL
                    AND ai_provider_version IS NULL)
            OR (ai_provider_category IS NOT NULL AND ai_provider IS NOT NULL AND raw_score IS NOT NULL)),
    ADD CONSTRAINT ck_scoring_answers_selected_source_metadata
        CHECK ((selected_score_source IS NULL AND selected_score_source_at IS NULL
                AND selected_score_source_by_public_id IS NULL)
            OR (selected_score_source IS NOT NULL AND selected_score_source_at IS NOT NULL
                AND selected_score_source_by_public_id IS NOT NULL)),
    ADD CONSTRAINT ck_scoring_answers_real_ai_selection
        CHECK (selected_score_source IS DISTINCT FROM 'AI'
            OR (ai_provider_category = 'REAL' AND raw_score IS NOT NULL));

CREATE TABLE examiner_assignment_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    tenant_id UUID NOT NULL,
    session_public_id UUID NOT NULL,
    created_by_public_id UUID NOT NULL,
    mode VARCHAR(16) NOT NULL CHECK (mode IN ('MANUAL', 'RANDOM')),
    status VARCHAR(16) NOT NULL CHECK (status IN ('PREVIEWED', 'COMMITTED', 'EXPIRED')),
    scope_snapshot_json TEXT NOT NULL,
    assignment_snapshot_json TEXT NOT NULL,
    random_seed UUID,
    preview_expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    committed_at TIMESTAMP WITH TIME ZONE,
    lock_version BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX idx_examiner_assignment_batch_session
    ON examiner_assignment_batches (tenant_id, session_public_id, created_at);

CREATE TABLE examiner_attempt_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    batch_public_id UUID NOT NULL,
    tenant_id UUID NOT NULL,
    session_public_id UUID NOT NULL,
    attempt_public_id UUID NOT NULL,
    examiner_public_id UUID NOT NULL,
    assigned_by_public_id UUID NOT NULL,
    assigned_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_examiner_assignment_session_attempt UNIQUE (session_public_id, attempt_public_id)
);
CREATE INDEX idx_examiner_assignment_examiner
    ON examiner_attempt_assignments (tenant_id, session_public_id, examiner_public_id);
CREATE INDEX idx_examiner_assignment_batch
    ON examiner_attempt_assignments (batch_public_id);

CREATE TABLE examiner_answer_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    answer_public_id UUID NOT NULL,
    attempt_public_id UUID NOT NULL,
    session_public_id UUID NOT NULL,
    tenant_id UUID NOT NULL,
    examiner_public_id UUID NOT NULL,
    score INTEGER NOT NULL CHECK (score BETWEEN 0 AND 100),
    status VARCHAR(16) NOT NULL CHECK (status = 'SUBMITTED'),
    submitted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    lock_version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_examiner_answer_score_answer UNIQUE (answer_public_id)
);
CREATE INDEX idx_examiner_score_attempt
    ON examiner_answer_scores (tenant_id, session_public_id, attempt_public_id);
CREATE INDEX idx_examiner_score_examiner
    ON examiner_answer_scores (tenant_id, session_public_id, examiner_public_id);

CREATE TABLE score_source_audits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    tenant_id UUID NOT NULL,
    session_public_id UUID NOT NULL,
    actor_public_id UUID NOT NULL,
    scope VARCHAR(16) NOT NULL CHECK (scope IN ('ALL', 'SECTION', 'TASK_TYPE')),
    scope_value VARCHAR(128),
    selected_source VARCHAR(16) NOT NULL CHECK (selected_source IN ('AI', 'EXAMINER')),
    affected_answer_count INTEGER NOT NULL CHECK (affected_answer_count >= 0),
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_score_source_audit_scope_value CHECK (
        (scope = 'ALL' AND scope_value IS NULL)
        OR (scope IN ('SECTION', 'TASK_TYPE') AND scope_value IS NOT NULL AND length(trim(scope_value)) > 0)
    )
);
CREATE INDEX idx_score_source_audit_session
    ON score_source_audits (tenant_id, session_public_id, occurred_at);

CREATE TABLE scoring_session_states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    tenant_id UUID NOT NULL,
    session_public_id UUID NOT NULL,
    publication_public_id UUID,
    publication_locked_at TIMESTAMP WITH TIME ZONE,
    lock_version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_scoring_session_state_tenant_session UNIQUE (tenant_id, session_public_id),
    CONSTRAINT ck_scoring_session_publication_lock CHECK (
        (publication_public_id IS NULL AND publication_locked_at IS NULL)
        OR (publication_public_id IS NOT NULL AND publication_locked_at IS NOT NULL)
    )
);
