-- media module (plans/modular-monolith Phase 04/A).
-- Hand-written to match what Hibernate derives from MediaObject (extends
-- shared.domain.BaseEntity), not copied from services/media (ddl-auto: update
-- there, no Flyway migration of its own).

CREATE TABLE IF NOT EXISTS media_objects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    tenant_id UUID NOT NULL,
    owner_public_id UUID NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    storage_key VARCHAR(255) NOT NULL UNIQUE,
    status VARCHAR(32) NOT NULL,
    audio_prompt BOOLEAN NOT NULL DEFAULT FALSE,
    duration_seconds INTEGER
);

CREATE INDEX IF NOT EXISTS idx_media_objects_owner ON media_objects (owner_public_id);
