-- itembank module (plans/modular-monolith Phase 05/A).
-- Hand-written to match what Hibernate derives from Question/QuestionOption
-- (extend shared.domain.BaseEntity), not copied from services/authoring
-- (ddl-auto: update there, no Flyway migration of its own).

CREATE TABLE IF NOT EXISTS questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    pte_task_type VARCHAR(64) NOT NULL,
    visibility VARCHAR(16) NOT NULL,
    tenant_id UUID,
    status VARCHAR(16) NOT NULL,
    title VARCHAR(255) NOT NULL,
    prompt_text TEXT,
    audio_prompt_ref UUID,
    image_prompt_ref UUID,
    reference_answer_text TEXT,
    correct_answer_text TEXT,
    min_word_count INTEGER,
    max_word_count INTEGER
);

CREATE INDEX IF NOT EXISTS idx_questions_tenant ON questions (tenant_id);
CREATE INDEX IF NOT EXISTS idx_questions_visibility ON questions (visibility);
CREATE INDEX IF NOT EXISTS idx_questions_task_type ON questions (pte_task_type);

CREATE TABLE IF NOT EXISTS question_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    question_id BIGINT NOT NULL REFERENCES questions (id),
    text TEXT NOT NULL,
    correct BOOLEAN NOT NULL,
    order_index INTEGER NOT NULL,
    blank_index INTEGER,
    correct_gap_index INTEGER
);

CREATE INDEX IF NOT EXISTS idx_options_question ON question_options (question_id);
