-- Student desktop lockdown observations belong to the attempt boundary.
-- They do not have a proctor_session_id and must not be fabricated as
-- proctor events merely to reuse the legacy hash-chain table.
CREATE TABLE IF NOT EXISTS attempt_security_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    attempt_id BIGINT NOT NULL REFERENCES exam_attempts (id),
    attempt_public_id UUID NOT NULL,
    session_public_id UUID NOT NULL,
    student_public_id UUID NOT NULL,
    tenant_id UUID NOT NULL,
    client_event_id VARCHAR(128) NOT NULL,
    violation_type VARCHAR(64) NOT NULL,
    severity VARCHAR(16) NOT NULL,
    detail TEXT,
    client_occurred_at TIMESTAMP WITH TIME ZONE,
    detected_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_attempt_security_events_attempt_client
        UNIQUE (attempt_id, client_event_id),
    CONSTRAINT ck_attempt_security_events_violation_type
        CHECK (violation_type IN (
            'LOCKDOWN_FULLSCREEN_EXIT',
            'LOCKDOWN_CLIPBOARD_PASTE',
            'LOCKDOWN_SHORTCUT_BLOCKED',
            'LOCKDOWN_FORBIDDEN_APP_DETECTED'
        )),
    CONSTRAINT ck_attempt_security_events_severity
        CHECK (severity IN ('WARNING', 'CRITICAL'))
);

CREATE INDEX IF NOT EXISTS idx_attempt_security_events_tenant_session_detected
    ON attempt_security_events (tenant_id, session_public_id, detected_at);

CREATE INDEX IF NOT EXISTS idx_attempt_security_events_attempt_detected
    ON attempt_security_events (attempt_public_id, detected_at);

CREATE INDEX IF NOT EXISTS idx_attempt_security_events_attempt_client
    ON attempt_security_events (attempt_id, client_event_id);
