-- Additive in-app inbox foundation. Existing notification_logs/email semantics are untouched.
-- Rollback: disable notification.inbox.enabled; retain durable records. No destructive down migration.
CREATE TABLE notification_inbox_contents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    event_key VARCHAR(255) NOT NULL UNIQUE,
    schema_version INTEGER NOT NULL CHECK (schema_version = 1),
    payload_hash VARCHAR(64) NOT NULL CHECK (length(payload_hash) = 64),
    notification_type VARCHAR(48) NOT NULL CHECK (notification_type IN ('APPLICATION_SUBMITTED','PLATFORM_ANNOUNCEMENT','SESSION_CLOSING_SOON','SESSION_GRADING_COMPLETED','COMMERCIAL_OUTCOME_CONFIRMED','ORDER_EXPIRED','SUBSCRIPTION_REVOKED')),
    category VARCHAR(32) NOT NULL CHECK (category IN ('SYSTEM_NOTICE','MAINTENANCE','SESSION','APPLICATION','BILLING')),
    importance VARCHAR(16) NOT NULL CHECK (importance IN ('INFO','IMPORTANT')),
    title VARCHAR(150) NOT NULL CHECK (length(trim(title)) > 0),
    body VARCHAR(5000) NOT NULL CHECK (length(trim(body)) > 0),
    target_type VARCHAR(32) NOT NULL CHECK (target_type IN ('APPLICATION','ANNOUNCEMENT','SESSION','ORDER','SUBSCRIPTION','QUOTA')),
    target_public_id UUID NOT NULL
);

CREATE TABLE notification_inbox_announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    author_user_public_id UUID NOT NULL REFERENCES users(public_id),
    title VARCHAR(150) NOT NULL,
    body VARCHAR(5000) NOT NULL,
    category VARCHAR(32) NOT NULL CHECK (category IN ('SYSTEM_NOTICE','MAINTENANCE')),
    importance VARCHAR(16) NOT NULL CHECK (importance IN ('INFO','IMPORTANT')),
    affected_from TIMESTAMPTZ,
    affected_until TIMESTAMPTZ,
    published_content_public_id UUID UNIQUE REFERENCES notification_inbox_contents(public_id),
    published_at TIMESTAMPTZ,
    correction_of_public_id UUID REFERENCES notification_inbox_announcements(public_id),
    version BIGINT NOT NULL DEFAULT 0,
    CHECK (affected_until IS NULL OR (affected_from IS NOT NULL AND affected_until > affected_from)),
    CHECK ((published_at IS NULL) = (published_content_public_id IS NULL))
);

CREATE TABLE notification_inbox_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    content_public_id UUID NOT NULL REFERENCES notification_inbox_contents(public_id),
    recipient_user_public_id UUID NOT NULL REFERENCES users(public_id),
    tenant_id UUID REFERENCES tenants(public_id),
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','PROCESSING','DELIVERED','FAILED','SUPPRESSED')),
    attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    next_attempt_at TIMESTAMPTZ NOT NULL,
    claim_token UUID,
    lease_until TIMESTAMPTZ,
    last_failure_code VARCHAR(64),
    completed_at TIMESTAMPTZ,
    -- No nullable tenant in uniqueness: platform admins are deduplicated too.
    UNIQUE (content_public_id, recipient_user_public_id),
    CHECK ((status = 'PROCESSING') = (claim_token IS NOT NULL AND lease_until IS NOT NULL))
);
CREATE INDEX idx_inbox_delivery_due ON notification_inbox_deliveries(next_attempt_at, id) WHERE status = 'PENDING';
CREATE INDEX idx_inbox_delivery_lease ON notification_inbox_deliveries(lease_until, id) WHERE status = 'PROCESSING';
CREATE INDEX idx_inbox_delivery_status ON notification_inbox_deliveries(status);

CREATE TABLE notification_inbox_streams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    recipient_user_public_id UUID NOT NULL UNIQUE REFERENCES users(public_id),
    tenant_id UUID REFERENCES tenants(public_id),
    last_sequence BIGINT NOT NULL DEFAULT 0 CHECK (last_sequence >= 0),
    read_revision BIGINT NOT NULL DEFAULT 0 CHECK (read_revision >= 0)
);

CREATE TABLE notification_inbox_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    delivery_public_id UUID NOT NULL UNIQUE REFERENCES notification_inbox_deliveries(public_id),
    content_public_id UUID NOT NULL REFERENCES notification_inbox_contents(public_id),
    recipient_user_public_id UUID NOT NULL REFERENCES notification_inbox_streams(recipient_user_public_id),
    tenant_id UUID REFERENCES tenants(public_id),
    sequence_no BIGINT NOT NULL CHECK (sequence_no > 0),
    delivered_at TIMESTAMPTZ NOT NULL,
    read_at TIMESTAMPTZ,
    UNIQUE (content_public_id, recipient_user_public_id),
    UNIQUE (recipient_user_public_id, sequence_no)
);
CREATE INDEX idx_inbox_item_history ON notification_inbox_items(recipient_user_public_id, tenant_id, sequence_no DESC);
CREATE INDEX idx_inbox_item_unread ON notification_inbox_items(recipient_user_public_id, tenant_id, sequence_no DESC) WHERE read_at IS NULL;
