-- Server-issued, recipient-bound page anchors for the personal inbox API.
-- The token is opaque to clients and expires; it never grants access outside its owner.
CREATE TABLE notification_inbox_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    recipient_user_public_id UUID NOT NULL REFERENCES users(public_id),
    tenant_id UUID REFERENCES tenants(public_id),
    upper_sequence BIGINT NOT NULL CHECK (upper_sequence >= 0),
    read_revision BIGINT NOT NULL CHECK (read_revision >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL CHECK (expires_at > created_at)
);
CREATE INDEX idx_inbox_snapshot_owner ON notification_inbox_snapshots(
    recipient_user_public_id, tenant_id, expires_at
);
