-- Freeze one immutable grading cohort per CLOSED exam session.
-- Outstanding attempts are dispositioned for this cohort only; attempt status is untouched.
CREATE TABLE session_grading_cohorts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    tenant_id UUID NOT NULL,
    session_public_id UUID NOT NULL,
    created_by_public_id UUID NOT NULL,
    cohort_version BIGINT NOT NULL DEFAULT 1 CHECK (cohort_version > 0),
    preview_version VARCHAR(128) NOT NULL,
    marking_mode VARCHAR(24) NOT NULL CHECK (marking_mode IN ('AI_ONLY','MANUAL_EXAMINER')),
    status VARCHAR(16) NOT NULL CHECK (status IN ('FROZEN','COMPLETED')),
    frozen_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    lock_version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_grading_cohort_session UNIQUE (tenant_id, session_public_id),
    CONSTRAINT ck_grading_cohort_completion CHECK (
        (status = 'FROZEN' AND completed_at IS NULL)
        OR (status = 'COMPLETED' AND completed_at IS NOT NULL)
    )
);

CREATE INDEX idx_grading_cohort_status ON session_grading_cohorts(status) WHERE deleted = FALSE;

CREATE TABLE session_grading_cohort_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    cohort_public_id UUID NOT NULL REFERENCES session_grading_cohorts(public_id),
    tenant_id UUID NOT NULL,
    session_public_id UUID NOT NULL,
    attempt_public_id UUID NOT NULL,
    student_public_id UUID NOT NULL,
    attempt_status_snapshot VARCHAR(16) NOT NULL,
    excluded BOOLEAN NOT NULL DEFAULT FALSE,
    disposition_reason VARCHAR(500),
    CONSTRAINT uq_grading_member_attempt UNIQUE (cohort_public_id, attempt_public_id),
    CONSTRAINT ck_grading_member_disposition CHECK (
        (excluded = FALSE AND disposition_reason IS NULL)
        OR (excluded = TRUE AND length(trim(disposition_reason)) > 0)
    )
);

CREATE INDEX idx_grading_member_attempt
    ON session_grading_cohort_members(tenant_id, session_public_id, attempt_public_id)
    WHERE deleted = FALSE;
