-- assessment module (plans/modular-monolith Phase 05/A).
-- Hand-written to match what Hibernate derives from ExamBlueprint/BlueprintItem/
-- ExamSnapshot/SnapshotItem (extend shared.domain.BaseEntity), not copied from
-- services/authoring (ddl-auto: update there, no Flyway migration of its own).

CREATE TABLE IF NOT EXISTS exam_blueprints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    name VARCHAR(255) NOT NULL,
    tenant_id UUID,
    status VARCHAR(16) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_blueprints_tenant ON exam_blueprints (tenant_id);

CREATE TABLE IF NOT EXISTS blueprint_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    blueprint_id BIGINT NOT NULL REFERENCES exam_blueprints (id),
    question_public_id UUID NOT NULL,
    section VARCHAR(16) NOT NULL,
    order_index INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_blueprint_items_blueprint ON blueprint_items (blueprint_id);

CREATE TABLE IF NOT EXISTS exam_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    name VARCHAR(255) NOT NULL,
    version INTEGER NOT NULL,
    source_blueprint_public_id UUID NOT NULL,
    tenant_id UUID
);

CREATE INDEX IF NOT EXISTS idx_snapshots_tenant ON exam_snapshots (tenant_id);

CREATE TABLE IF NOT EXISTS snapshot_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    snapshot_id BIGINT NOT NULL REFERENCES exam_snapshots (id),
    source_question_public_id UUID NOT NULL,
    pte_task_type VARCHAR(64) NOT NULL,
    section VARCHAR(16) NOT NULL,
    order_index INTEGER NOT NULL,
    title VARCHAR(255) NOT NULL,
    prompt_text TEXT,
    audio_prompt_ref UUID,
    image_prompt_ref UUID,
    reference_answer_text TEXT,
    correct_answer_text TEXT,
    min_word_count INTEGER,
    max_word_count INTEGER,
    options_json TEXT
);

CREATE INDEX IF NOT EXISTS idx_snapshot_items_snapshot ON snapshot_items (snapshot_id);
