-- Passwordless practice identity/challenge storage and canonical student links.
-- Raw verification codes are never stored; only a BCrypt hash is persisted.
-- Rollback policy: disable the practice auth feature and retain audit/history;
-- no destructive down migration is used.

CREATE TABLE practice_identities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    normalized_email_hash VARCHAR(64) NOT NULL UNIQUE,
    status VARCHAR(16) NOT NULL,
    shell_user_id BIGINT REFERENCES users (id),
    verified_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_practice_identities_shell_user
    ON practice_identities (shell_user_id);

CREATE TABLE practice_identity_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    identity_id BIGINT NOT NULL REFERENCES practice_identities (id),
    user_public_id UUID NOT NULL,
    tenant_id UUID NOT NULL,
    status VARCHAR(16) NOT NULL,
    linked_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_practice_identity_memberships_link UNIQUE (identity_id, user_public_id)
);

CREATE INDEX idx_practice_identity_memberships_identity
    ON practice_identity_memberships (identity_id);

CREATE INDEX idx_practice_identity_memberships_tenant
    ON practice_identity_memberships (tenant_id);

CREATE TABLE practice_email_challenges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    identity_id BIGINT NOT NULL REFERENCES practice_identities (id),
    code_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    consumed_at TIMESTAMP WITH TIME ZONE,
    failed_attempts INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX idx_practice_email_challenges_identity_created
    ON practice_email_challenges (identity_id, created_at);
