-- Standalone practice product/session boundary.
-- Rollback policy: disable practice entry and keep additive history; do not
-- drop sessions, links or confidence data after a failed rollout.

CREATE TABLE practice_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    student_public_id UUID NOT NULL,
    identity_public_id UUID NOT NULL,
    tenant_id UUID NOT NULL,
    product_code VARCHAR(64) NOT NULL,
    title VARCHAR(128) NOT NULL,
    time_limit_seconds INTEGER NOT NULL,
    catalog_version VARCHAR(32) NOT NULL,
    selected_task_types TEXT,
    client_capabilities TEXT,
    source_type VARCHAR(16) NOT NULL,
    status VARCHAR(16) NOT NULL,
    start_idempotency_key VARCHAR(128) NOT NULL,
    start_request_hash VARCHAR(64) NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE,
    deadline_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    discarded_at TIMESTAMP WITH TIME ZONE,
    version BIGINT,
    CONSTRAINT uk_practice_sessions_student_start_key
        UNIQUE (student_public_id, start_idempotency_key)
);

CREATE INDEX idx_practice_sessions_student
    ON practice_sessions (student_public_id);

CREATE INDEX idx_practice_sessions_tenant_status
    ON practice_sessions (tenant_id, status);

CREATE TABLE practice_session_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    practice_session_id BIGINT NOT NULL REFERENCES practice_sessions (id),
    exam_attempt_public_id UUID NOT NULL,
    source_type VARCHAR(16) NOT NULL,
    CONSTRAINT uk_practice_session_attempt
        UNIQUE (practice_session_id, exam_attempt_public_id)
);

CREATE INDEX idx_practice_session_attempts_session
    ON practice_session_attempts (practice_session_id);

CREATE INDEX idx_practice_session_attempts_attempt
    ON practice_session_attempts (exam_attempt_public_id);

CREATE TABLE practice_session_operations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    practice_session_id BIGINT NOT NULL REFERENCES practice_sessions (id),
    operation_type VARCHAR(16) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    CONSTRAINT uk_practice_session_operation_key
        UNIQUE (practice_session_id, operation_type, idempotency_key)
);

CREATE INDEX idx_practice_session_operations_session
    ON practice_session_operations (practice_session_id);

ALTER TABLE attempt_answers
    ADD COLUMN confidence VARCHAR(16);
