-- Durable objective-task boundary for standalone practice sessions.
-- Rollback policy: disable practice entry and retain student answer history;
-- do not drop session items or payloads during a failed rollout.

ALTER TABLE practice_sessions
    ADD COLUMN last_activity_at TIMESTAMP WITH TIME ZONE;

CREATE TABLE practice_session_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    practice_session_id BIGINT NOT NULL REFERENCES practice_sessions (id),
    order_index INTEGER NOT NULL,
    task_code VARCHAR(64) NOT NULL,
    display_name VARCHAR(128) NOT NULL,
    section VARCHAR(32) NOT NULL,
    renderer_key VARCHAR(128) NOT NULL,
    contract_version INTEGER,
    answer_schema_version INTEGER,
    status VARCHAR(16) NOT NULL,
    saved_payload TEXT,
    confidence VARCHAR(16),
    answered_at TIMESTAMP WITH TIME ZONE,
    skipped_at TIMESTAMP WITH TIME ZONE,
    version BIGINT,
    CONSTRAINT uk_practice_session_item_order UNIQUE (practice_session_id, order_index)
);

CREATE INDEX idx_practice_session_items_session
    ON practice_session_items (practice_session_id);

CREATE INDEX idx_practice_session_items_status
    ON practice_session_items (practice_session_id, status);
