-- session module (plans/modular-monolith Phase 06).
-- Hand-written to match what Hibernate derives from ExamSession/ExamPolicy
-- (embedded)/SessionComposition/Enrollment/ProctorAssignment (extend
-- shared.domain.BaseEntity), not copied from services/scheduling (ddl-auto:
-- update there, no Flyway migration of its own).
--
-- No snapshot_refs/snapshot_ref_items table — session reads the snapshot
-- summary from assessment via an in-process call each time it's needed
-- (AssessmentService.getSummary), replacing the cache-table + outbox-consumer
-- pair the source microservice needed to stay in sync across a network call.

CREATE TABLE IF NOT EXISTS exam_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    name VARCHAR(255) NOT NULL,
    tenant_id UUID NOT NULL,
    snapshot_public_id UUID NOT NULL,
    opens_at TIMESTAMP WITH TIME ZONE NOT NULL,
    closes_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(16) NOT NULL,
    capacity INTEGER,
    replay_policy_type VARCHAR(16),
    replay_policy_limit INTEGER,
    device_check_required BOOLEAN,
    proctor_required BOOLEAN,
    answer_integrity_level VARCHAR(16),
    lockdown_mode VARCHAR(16)
);

CREATE INDEX IF NOT EXISTS idx_sessions_tenant ON exam_sessions (tenant_id);

CREATE TABLE IF NOT EXISTS session_compositions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    session_id BIGINT NOT NULL REFERENCES exam_sessions (id),
    task_type VARCHAR(64) NOT NULL,
    section VARCHAR(16) NOT NULL,
    order_index INTEGER NOT NULL,
    timing_override_seconds INTEGER,
    max_play_count INTEGER
);

CREATE INDEX IF NOT EXISTS idx_compositions_session ON session_compositions (session_id);

CREATE TABLE IF NOT EXISTS enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    session_id BIGINT NOT NULL REFERENCES exam_sessions (id),
    student_public_id UUID NOT NULL,
    tenant_id UUID NOT NULL,
    UNIQUE (session_id, student_public_id)
);

CREATE INDEX IF NOT EXISTS idx_enrollments_session ON enrollments (session_id);

CREATE TABLE IF NOT EXISTS proctor_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    session_id BIGINT NOT NULL REFERENCES exam_sessions (id),
    proctor_public_id UUID NOT NULL,
    tenant_id UUID NOT NULL,
    role VARCHAR(32),
    UNIQUE (session_id, proctor_public_id)
);

CREATE INDEX IF NOT EXISTS idx_proctor_assignments_session ON proctor_assignments (session_id);
