-- attempt module (plans/modular-monolith Phase 07 ★).
-- Hand-written to match what Hibernate derives from ExamAttempt/AttemptAnswer/
-- AttemptHeartbeat/PinnedExamSnapshot/PinnedItem (extend shared.domain.BaseEntity),
-- not copied from services/exam-delivery (ddl-auto: update there, no Flyway
-- migration of its own).

CREATE TABLE IF NOT EXISTS exam_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    session_public_id UUID NOT NULL,
    student_public_id UUID NOT NULL,
    tenant_id UUID NOT NULL,
    status VARCHAR(16) NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE,
    submitted_at TIMESTAMP WITH TIME ZONE,
    exam_end_time TIMESTAMP WITH TIME ZONE,
    device_check_passed_at TIMESTAMP WITH TIME ZONE,
    current_order_index INTEGER NOT NULL DEFAULT 0,
    play_count INTEGER NOT NULL DEFAULT 0,
    last_play_request_id VARCHAR(255),
    last_play_allowed BOOLEAN,
    active_section VARCHAR(255),
    section_started_at TIMESTAMP WITH TIME ZONE,
    version BIGINT,
    UNIQUE (session_public_id, student_public_id)
);

CREATE INDEX IF NOT EXISTS idx_attempts_tenant ON exam_attempts (tenant_id);

CREATE TABLE IF NOT EXISTS pinned_exam_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    attempt_id BIGINT UNIQUE REFERENCES exam_attempts (id),
    source_snapshot_public_id UUID NOT NULL,
    source_session_public_id UUID NOT NULL,
    tenant_id UUID NOT NULL,
    replay_policy_type VARCHAR(16) NOT NULL,
    replay_policy_limit INTEGER,
    device_check_required BOOLEAN NOT NULL,
    proctor_required BOOLEAN NOT NULL,
    answer_integrity_level VARCHAR(16) NOT NULL,
    lockdown_mode VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS pinned_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    pinned_snapshot_id BIGINT NOT NULL REFERENCES pinned_exam_snapshots (id),
    order_index INTEGER NOT NULL,
    section VARCHAR(16) NOT NULL,
    task_type VARCHAR(64) NOT NULL,
    title VARCHAR(255) NOT NULL,
    prompt_text TEXT,
    audio_prompt_ref UUID,
    image_prompt_ref UUID,
    reference_answer_text TEXT,
    correct_answer_text TEXT,
    min_word_count INTEGER,
    max_word_count INTEGER,
    options_json TEXT,
    prep_seconds INTEGER NOT NULL,
    response_seconds INTEGER NOT NULL,
    max_play_count_override INTEGER,
    audio_url TEXT,
    audio_url_expires_at TIMESTAMP WITH TIME ZONE,
    pre_listen_seconds INTEGER,
    pre_record_seconds INTEGER,
    image_url TEXT,
    image_url_expires_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_pinned_items_snapshot ON pinned_items (pinned_snapshot_id);

CREATE TABLE IF NOT EXISTS attempt_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    attempt_id BIGINT NOT NULL REFERENCES exam_attempts (id),
    pinned_item_id BIGINT NOT NULL REFERENCES pinned_items (id),
    payload TEXT,
    status VARCHAR(16) NOT NULL,
    expired BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE (attempt_id, pinned_item_id)
);

CREATE INDEX IF NOT EXISTS idx_answers_attempt ON attempt_answers (attempt_id);

CREATE TABLE IF NOT EXISTS attempt_heartbeats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    attempt_id BIGINT UNIQUE REFERENCES exam_attempts (id),
    last_seen_at TIMESTAMP WITH TIME ZONE NOT NULL
);
