package com.pte.notification.domain.enums;

public enum NotificationType {
    STUDENT_ENROLLED,
    ATTEMPT_PUBLISHED,
    VIOLATION_DETECTED,
    SESSION_CANCELLED,
    TENANT_APPLICATION_SUBMITTED,
    TENANT_APPLICATION_APPROVED,
    TENANT_APPLICATION_REJECTED
}
