[CmdletBinding()]
param(
    [string]$PostgresContainer = "pte-postgres",
    [switch]$SkipUrlCheck
)

# Loads the DEMO22 question bank (3 questions for each of the 22 scored PTE task types,
# 66 total) into the local Postgres of the docker compose stack.
#
# Needs only: Docker, the stack running (the app must have started once so Hibernate
# created the schema) and this repo. No Cloudinary credentials: the media urls are in the seed.
# Idempotent - safe to run any number of times.
#
#   .\scripts\demo22\seed-demo22-questions.ps1

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$seedDir = Join-Path $scriptDir "data"
$sqlPath = Join-Path $seedDir "demo22-seed.sql"
if (-not (Test-Path $sqlPath)) { throw "Missing $sqlPath (generated by scripts/demo22/tools/build-demo22-questions.js)" }

if (-not $SkipUrlCheck) {
    Write-Host "== Checking media urls =="
    $questions = (Get-Content -Raw -Path (Join-Path $seedDir "demo22-questions.json") | ConvertFrom-Json).questions
    $mediaMap = Get-Content -Raw -Path (Join-Path $seedDir "demo22-media.json") | ConvertFrom-Json
    $urls = @($questions | ForEach-Object {
            foreach ($kind in "audio", "image") {
                $media = $_.$kind
                if ($null -eq $media) { continue }
                if ($media.localFile) { $mediaMap.($media.localFile).url } else { $media.url }
            }
        } | Sort-Object -Unique)
    $broken = @()
    foreach ($url in $urls) {
        $status = & curl.exe --silent --head --location --max-time 20 --output NUL --write-out "%{http_code}" $url
        if ($status -notmatch "^2") { $broken += "$status $url" }
    }
    if ($broken.Count -gt 0) {
        $broken | ForEach-Object { Write-Warning $_ }
        throw "$($broken.Count) of $($urls.Count) media urls are not reachable. Fix them, or rerun with -SkipUrlCheck to seed anyway."
    }
    Write-Host "  $($urls.Count) media urls reachable"
}

Write-Host "== Loading DEMO22 questions into $PostgresContainer =="
$running = & docker ps --filter "name=^/$PostgresContainer$" --format "{{.Names}}"
if ($running -ne $PostgresContainer) { throw "Container '$PostgresContainer' is not running. Start the stack first (see README)." }

# Windows PowerShell 5.1 reads BOM-less files as ANSI and pipes to native commands in the console
# code page, which turns typographic quotes and accents into "?". Read and write UTF-8 explicitly.
$OutputEncoding = New-Object System.Text.UTF8Encoding($false)
[IO.File]::ReadAllText($sqlPath, $OutputEncoding) |
    & docker exec -i $PostgresContainer sh -c 'psql -v ON_ERROR_STOP=1 -q -U $POSTGRES_USER -d ${POSTGRES_DB:-pte}'
if ($LASTEXITCODE -ne 0) { throw "psql failed (exit $LASTEXITCODE); nothing was committed" }

$summary = "select pte_task_type, count(*) from questions where title like 'DEMO22 - %' and deleted = false group by 1 order by 1;" |
    & docker exec -i $PostgresContainer sh -c 'psql -U $POSTGRES_USER -d ${POSTGRES_DB:-pte} -t -A'
if ($LASTEXITCODE -ne 0) { throw "Summary query failed (exit $LASTEXITCODE)" }
Write-Host "== Questions per task type =="
$summary | ForEach-Object { Write-Host "  $_" }
Write-Host "Done: $(@($summary).Count) task types seeded."
