'use strict';
// Renders the idempotent DEMO22 seed SQL from the question list built by build-demo22-questions.js.
// The question API only accepts audio/wav media while the question bank is mp3, so (like
// pte-doc's local-question-seed.sql) the portable seed is plain SQL with deterministic UUIDs.
const crypto = require('crypto');

// ---- SQL seed ---------------------------------------------------------------------------
// The question API only accepts audio/wav media, while the question bank's audio is mp3, so
// (like pte-doc's local-question-seed.sql) the portable seed is plain idempotent SQL.
const NAMESPACE = Buffer.from('b3d5c2a1e4f64d0a9c7e5a1f2d3b4c5e', 'hex');
const OWNER = '7d1b4c75-2d46-5a4f-8ad8-4c9d9b8f0001'; // same reserved owner as local-question-seed.sql
const SEED_TIME = "TIMESTAMPTZ '2026-10-06 00:00:00+00'";
// Speaking prep timing needs audio.duration_seconds (MissingAudioDurationException otherwise);
// external mp3 lengths are not known, so use the per-type approximations the repo seed uses.
const EXTERNAL_DURATION_SECONDS = {
  REPEAT_SENTENCE: 6, RE_TELL_LECTURE: 72, ANSWER_SHORT_QUESTION: 4, RESPOND_TO_A_SITUATION: 15,
  SUMMARIZE_SPOKEN_TEXT: 75, MC_LISTENING_SINGLE: 50, MC_LISTENING_MULTIPLE: 60,
  HIGHLIGHT_CORRECT_SUMMARY: 60, SELECT_MISSING_WORD: 40, WRITE_FROM_DICTATION: 5
};

const uuidV5 = (name) => {
  const hash = crypto.createHash('sha1').update(NAMESPACE).update(name).digest();
  hash[6] = (hash[6] & 0x0f) | 0x50;
  hash[8] = (hash[8] & 0x3f) | 0x80;
  const h = hash.subarray(0, 16).toString('hex');
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-${h.slice(12, 16)}-${h.slice(16, 20)}-${h.slice(20)}`;
};
const text = (v) => (v === null || v === undefined ? 'NULL'
  : `E'${String(v).replace(/\\/g, '\\\\').replace(/'/g, "''").replace(/\n/g, '\\n')}'`);
const num = (v) => (v === null || v === undefined ? 'NULL' : String(v));
const uuidLit = (v) => (v ? `'${v}'::uuid` : 'NULL');

function mediaRow(q, kind) {
  const media = q[kind];
  if (!media) return null;
  const isAudio = kind === 'audio';
  const external = !media.localFile;
  const urlHash = crypto.createHash('sha256').update(media.url).digest('hex');
  const storageKey = external ? `external-seed/${urlHash}` : media.publicId;
  return {
    id: uuidV5(`media:${q.key}:${kind}`),
    contentType: media.contentType,
    storageKey,
    audioPrompt: isAudio,
    duration: isAudio ? (external ? EXTERNAL_DURATION_SECONDS[q.taskTypeKey] ?? null : media.durationSeconds) : null,
    cloudinaryPublicId: storageKey,
    resourceType: external ? 'external' : (isAudio ? 'video' : 'image'),
    url: media.url,
    assetId: external ? null : media.assetId || null,
    sizeBytes: external ? null : media.sizeBytes || null
  };
}

function buildSql(questions) {
  const mediaRows = [];
  const questionRows = [];
  const optionRows = [];
  for (const q of questions) {
    const audio = mediaRow(q, 'audio');
    const image = mediaRow(q, 'image');
    if (audio) mediaRows.push(audio);
    if (image) mediaRows.push(image);
    const id = uuidV5(`question:${q.key}`);
    questionRows.push(`  (${uuidLit(id)}, ${SEED_TIME}, ${SEED_TIME}, FALSE, ${text(q.taskTypeKey)}, ${text(q.taskTypeKey)}, ${text(q.section)}, 'SHARED', NULL, 'APPROVED', ${uuidLit(id)}, 1, NULL, TRUE, 0, NULL, ${text(q.title)}, ${text(q.promptText)}, ${uuidLit(audio && audio.id)}, ${uuidLit(image && image.id)}, ${text(q.referenceAnswerText)}, ${text(q.correctAnswerText)}, ${num(q.minWordCount)}, ${num(q.maxWordCount)})`);
    for (const option of q.options) {
      optionRows.push(`  (${uuidLit(uuidV5(`option:${q.key}:${option.orderIndex}`))}, ${uuidLit(id)}, ${SEED_TIME}, ${SEED_TIME}, FALSE, ${text(option.text)}, ${option.correct ? 'TRUE' : 'FALSE'}, ${option.orderIndex}, ${num(option.blankIndex)}, ${num(option.correctGapIndex)})`);
    }
  }
  const mediaValues = mediaRows.map((m) => `  (${uuidLit(m.id)}, ${SEED_TIME}, ${SEED_TIME}, FALSE, NULL, '${OWNER}'::uuid, ${text(m.contentType)}, ${text(m.storageKey)}, 'UPLOADED', ${m.audioPrompt ? 'TRUE' : 'FALSE'}, ${num(m.duration)}, ${text(m.cloudinaryPublicId)}, ${text(m.resourceType)}, ${text(m.url)}, ${text(m.assetId)}, ${num(m.sizeBytes)})`);
  const distinctTypes = new Set(questions.map((q) => q.taskTypeKey)).size;
  return `-- DEMO22 seed: ${questions.length} questions (3 per scored task type + 1 Personal Introduction), ${optionRows.length} options, ${mediaRows.length} media rows.
-- GENERATED by scripts/demo22/tools/build-demo22-questions.js from demo22-questions.json - do not edit by hand.
-- Idempotent (deterministic UUIDs, ON CONFLICT). Local/demo only; contains no secrets.
-- Run with scripts/demo22/seed-demo22-questions.ps1 against a stack whose app has already created its schema.

SET client_encoding = 'UTF8';
BEGIN;
SET LOCAL lock_timeout = '5s';

DO $$
BEGIN
    IF to_regclass('public.questions') IS NULL OR to_regclass('public.question_options') IS NULL
       OR to_regclass('public.media_objects') IS NULL OR to_regclass('public.question_types') IS NULL THEN
        RAISE EXCEPTION 'Schema is missing; start the app once so the migrations run, then retry';
    END IF;
END $$;

INSERT INTO media_objects (public_id, created_at, updated_at, deleted, tenant_id, owner_public_id, content_type, storage_key, status, audio_prompt, duration_seconds, cloudinary_public_id, cloudinary_resource_type, secure_url, asset_id, size_bytes) VALUES
${mediaValues.join(',\n')}
ON CONFLICT (public_id) DO UPDATE SET
    updated_at = EXCLUDED.updated_at, content_type = EXCLUDED.content_type, storage_key = EXCLUDED.storage_key,
    status = EXCLUDED.status, audio_prompt = EXCLUDED.audio_prompt, duration_seconds = EXCLUDED.duration_seconds,
    cloudinary_public_id = EXCLUDED.cloudinary_public_id, cloudinary_resource_type = EXCLUDED.cloudinary_resource_type,
    secure_url = EXCLUDED.secure_url, asset_id = EXCLUDED.asset_id, size_bytes = EXCLUDED.size_bytes;

INSERT INTO questions (public_id, created_at, updated_at, deleted, pte_task_type, task_type_key, task_type_section, visibility, tenant_id, status, revision_group_public_id, revision_number, supersedes_public_id, is_current, version, rejection_reason, title, prompt_text, audio_prompt_ref, image_prompt_ref, reference_answer_text, correct_answer_text, min_word_count, max_word_count) VALUES
${questionRows.join(',\n')}
ON CONFLICT (public_id) DO UPDATE SET
    updated_at = EXCLUDED.updated_at, deleted = FALSE, status = EXCLUDED.status, visibility = EXCLUDED.visibility,
    is_current = EXCLUDED.is_current, title = EXCLUDED.title, prompt_text = EXCLUDED.prompt_text,
    audio_prompt_ref = EXCLUDED.audio_prompt_ref, image_prompt_ref = EXCLUDED.image_prompt_ref,
    reference_answer_text = EXCLUDED.reference_answer_text, correct_answer_text = EXCLUDED.correct_answer_text,
    min_word_count = EXCLUDED.min_word_count, max_word_count = EXCLUDED.max_word_count;

DELETE FROM question_options existing
 USING questions question
 WHERE existing.question_id = question.id AND question.title LIKE 'DEMO22 - %';

INSERT INTO question_options (public_id, created_at, updated_at, deleted, question_id, text, correct, order_index, blank_index, correct_gap_index)
SELECT seed.public_id, seed.created_at, seed.updated_at, seed.deleted, question.id, seed.text, seed.correct, seed.order_index, seed.blank_index, seed.correct_gap_index
  FROM (VALUES
${optionRows.join(',\n')}
  ) AS seed(public_id, question_public_id, created_at, updated_at, deleted, text, correct, order_index, blank_index, correct_gap_index)
  JOIN questions question ON question.public_id = seed.question_public_id
ON CONFLICT (public_id) DO UPDATE SET
    updated_at = EXCLUDED.updated_at, question_id = EXCLUDED.question_id, text = EXCLUDED.text,
    correct = EXCLUDED.correct, order_index = EXCLUDED.order_index,
    blank_index = EXCLUDED.blank_index, correct_gap_index = EXCLUDED.correct_gap_index;

DO $$
DECLARE question_count BIGINT; option_count BIGINT; type_count BIGINT;
BEGIN
    SELECT COUNT(*), COUNT(DISTINCT pte_task_type) INTO question_count, type_count
      FROM questions WHERE title LIKE 'DEMO22 - %' AND deleted = FALSE;
    SELECT COUNT(*) INTO option_count
      FROM question_options o JOIN questions q ON q.id = o.question_id WHERE q.title LIKE 'DEMO22 - %';
    IF question_count <> ${questions.length} OR type_count <> ${distinctTypes} OR option_count <> ${optionRows.length} THEN
        RAISE EXCEPTION 'DEMO22 seed verification failed: questions=%, task types=%, options=%', question_count, type_count, option_count;
    END IF;
END $$;

COMMIT;
`;
}


module.exports = { buildSql };
